experiment_name: "Experiment Using BART-LARGE-MNLI"
learning_rate: 1e-3
batch_size: 16
epochs: 100
model_path: "facebook/bart-large-mnli"
max_len: 512
model_name: "bart"
log_dir: "experiments-not-finetuning/bart-experiment-p2plus-alpha4/logs"
checkpoint_dir: "checkpoints"