experiment_name: "Experiment Using Modern BERT"
learning_rate: 1e-3
batch_size: 64
epochs: 100
model_path: "answerdotai/ModernBERT-large"
max_len: 512
model_name: "modern-bert"
log_dir: "experiments-not-finetuning/deepseek-modernbert-experiment-p5-alpha5/logs"
checkpoint_dir: "checkpoints"