experiment_name: "Experiment Using BART-LARGE-MNLI"
learning_rate: 1e-5
batch_size: 8
epochs: 100
model_path: "facebook/bart-large-mnli"
max_len: 512
model_name: "bart"
log_dir: "experiments-finetuning/bart-experiment-p5-alpha5/logs"
checkpoint_dir: "checkpoints"