experiment_name: "Experiment Using BART-LARGE-MNLI"
learning_rate: 1e-3
batch_size: 128
epochs: 100
model_path: "facebook/bart-large-mnli"
max_len: 512
model_name: "bart"
log_dir: "experiments-not-finetuning/deepseek-bart-experiment-p5-alpha3/logs"
checkpoint_dir: "checkpoints"