experiment_name: "Experiment Using BART-LARGE-MNLI"
learning_rate: 1e-5
batch_size: 16
epochs: 1
model_path: "facebook/bart-large-mnli"
max_len: 512
model_name: "bart"
log_dir: "experiments-not-finetuning/bart-experiment-p3-alpha3/logs"
checkpoint_dir: "checkpoints"