experiment_name: "Experiment using Distil-BERT"
learning_rate: 1e-3
batch_size: 128
epochs: 100
model_path: "distilbert-base-uncased"
model_name: "distil-bert"
max_len: 512
log_dir: "experiments-not-finetuning/distil-experiment-p5-alpha5/logs"
checkpoint_dir: "checkpoints"