experiment_name: "Experiment Using Modern BERT"
learning_rate: 1e-2
batch_size: 1024
epochs: 100
model_path: "answerdotai/ModernBERT-large"
max_len: 512
model_name: "modern-bert"
log_dir: "experiments-not-finetuning/openai-modernbert-experiment-p3-alpha5/logs"
checkpoint_dir: "checkpoints"