experiment_name: "Experiment Using Modern BERT"
learning_rate: 1e-5
batch_size: 8
epochs: 1
model_path: "answerdotai/ModernBERT-large"
max_len: 512
model_name: "modern-bert"
log_dir: "experiments-not-finetuning/openai-modernbert-experiment-p3-alpha3/logs"
checkpoint_dir: "checkpoints"